name: 'Whitesource Unified Agent Scan'
author: 'Azeem Shezad Ilyas'
description: 'Run a scan using the Whitesource unified agent. This version uses auto-resolve dependencies so it does not require a config file.'
inputs:
  wssURL:
    description: 'The relevent URL to your orgs WS Server. Can be found under the Integrate tab of your Whitesource dashboard (e.g. https://app-eu.whitesourcesoftware.com/agent).'
    required: true
  apiKey:
    description: 'API key from Whitesource.'
    required: true
  productName:
    description: 'Name of the Product that this project falls under.'
    required: false
  projectName:
    description: 'Name of the Project. It could be just repository name.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'tool'
  color: 'yellow'
