# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Whitesource Action
      uses: ./
      with:
        wssUrl: https://app-eu.whitesourcesoftware.com/agent
        apiKey: fakeKey123 #Fetch from Github Secrets
        productName: TestProduct
        projectName: WSS-Action
